export enum DEPARTMENT {
  UNKNOWN = "UNKNOWN",
  BANQUET_HALL = "BANQUET_HALL",
  VEG_RESTAURANT = "VEG_RESTAURANT",
  AC_RESTAURANT = "AC_RESTAURANT",
  OPEN_AIR = "OPEN_AIR",
  CAFE_BAAR_AREA = "CAFE_BAAR_AREA",
  DANCE_FLOOR = "DANCE_FLOOR",
}

export enum KITCHEN {
  UNKNOWN = "UNKNOWN",
  INDIAN = "INDIAN",
  CHINESE = "CHINESE",
  TANDOOR = "TANDOOR",
  PANTRY = "PANTRY",
  SOUTH_INDIAN = "SOUTH_INDIAN",
  CONTINENTAL = "CONTINENTAL",
}

export enum PRODUCT_CATEGORIES {
  UNKNOWN = 0,
  NORTH_INDIAN = 1,
  SOUTH_INDIAN,
  BANGALIES,
  CHINESE,
  PIZZA,
  BURGER,
  ICE_CREAM,
  DRINKING_WATER,
  DESSERTS,
  BIRYANI,
}

export enum CAFE_SKILL {
  UNKNOWN = 0,
  NORTH_INDIAN = 1,
  SOUTH_INDIAN,
  BANGALIES,
  CHINESE,
  PIZZA,
  BURGER,
  ICE_CREAM,
  DRINKING_WATER,
  DESSERTS,
  BIRYANI,
}

export enum PRODUCT_QUALITIES {
  HALF = 0,
  MEDIUM = 1,
  FULL,
}

export enum ORDER_STATUS {
  UNKNOWN = "UNKNOWN",
  WAITING = "WAITING",
  PLACED = "PLACED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PREPARING = "PREPARING",
  READY_TO_SERVE = "READY_TO_SERVE",
  COMPLETED = "COMPLETED",
}
