import {
  ADMIN,
  DIRECTOR,
  OPERATIONAL_MANAGER,
  FB_MANAGER,
  CASHIER,
  MANAGER,
  CAPTAIN,
  ORDER,
  INVENTORY,
  REPORTS,
  FOOD,
} from "./config";

export default [
  {
    name: DIRECTOR,
    permissions: {
      CREATE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
      ],
      READ: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
      ],
      UPDATE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
      ],
      DELETE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
      ],
    },
  },
  {
    name: OPERATIONAL_MANAGER,
    permissions: {
      CREATE: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        INVENTORY,
        REPORTS,
      ],
      READ: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
      ],
      UPDATE: [FB_MANAGER, CASHIER, ADMIN, MANAGER, CAPTAIN],
      DELETE: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        MANAGER,
        CAPTAIN,
        INVENTORY,
        REPORTS,
      ],
    },
  },
  {
    name: ADMIN,
    permissions: {
      CREATE: [
        FB_MANAGER,
        CASHIER,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
      ],
      READ: [
        FB_MANAGER,
        CASHIER,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
      ],
      UPDATE: [
        FB_MANAGER,
        CASHIER,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
      ],
      DELETE: [
        FB_MANAGER,
        CASHIER,
        MANAGER,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
      ],
    },
  },
  {
    name: FB_MANAGER,
    permissions: {
      CREATE: [CASHIER, MANAGER, CAPTAIN, ORDER, INVENTORY],
      READ: [CASHIER, MANAGER, CAPTAIN, ORDER, INVENTORY, FOOD],
      UPDATE: [CASHIER, MANAGER, CAPTAIN, ORDER, INVENTORY],
      DELETE: [CASHIER, MANAGER, CAPTAIN],
    },
  },
  {
    name: CASHIER,
    permissions: {
      CREATE: [MANAGER, CAPTAIN, ORDER],
      READ: [MANAGER, CAPTAIN, ORDER],
      UPDATE: [MANAGER, CAPTAIN, ORDER],
    },
  },
  {
    name: MANAGER,
    permissions: {
      CREATE: [CAPTAIN, ORDER],
      READ: [CAPTAIN, ORDER],
      UPDATE: [CAPTAIN, ORDER],
    },
  },
];
