import {
  ADMIN,
  DIRECTOR,
  OPERATIONAL_MANAGER,
  FB_MANAGER,
  CASHIER,
  CAPTAIN,
  ORDER,
  INVENTORY,
  REPORTS,
  FOOD,
  TABLE,
  WAITER,
  KITCHEN,
} from "./config";

export default [
  {
    name: DIRECTOR,
    permissions: {
      CREATE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        CAPTAIN,
        TABLE,
        WAITER,
        KITCHEN,
      ],
      READ: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      UPDATE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        TABLE,
      ],
      DELETE: [
        OPERATIONAL_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        TABLE,
      ],
    },
  },
  {
    name: OPERATIONAL_MANAGER,
    permissions: {
      CREATE: [
        FB_MANAGER,
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      READ: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      UPDATE: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      DELETE: [
        FB_MANAGER,
        CASHIER,
        ADMIN,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
    },
  },
  {
    name: ADMIN,
    permissions: {
      CREATE: [
        FB_MANAGER,
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      READ: [
        FB_MANAGER,
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      UPDATE: [
        FB_MANAGER,
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      DELETE: [
        FB_MANAGER,
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
    },
  },
  {
    name: FB_MANAGER,
    permissions: {
      CREATE: [
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      READ: [
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      UPDATE: [
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
      DELETE: [
        CASHIER,
        WAITER,
        KITCHEN,
        CAPTAIN,
        ORDER,
        INVENTORY,
        REPORTS,
        FOOD,
        TABLE,
      ],
    },
  },
  {
    name: CASHIER,
    permissions: {
      CREATE: [WAITER, KITCHEN, CAPTAIN, ORDER],
      READ: [WAITER, KITCHEN, CAPTAIN, ORDER],
      UPDATE: [WAITER, KITCHEN, CAPTAIN, ORDER],
    },
  },
  {
    name: CAPTAIN,
    permissions: {
      CREATE: [WAITER, ORDER],
      READ: [WAITER, ORDER],
      UPDATE: [WAITER, ORDER],
    },
  },
];
